name: build
on: [push]
jobs:
  test-docs:
    name: Test HungryMoose Docs Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '12.x'
      - name: Run Tests
        run: ./gradlew clean check
        working-directory: ./hungry-moose-docs
  test-test:
    name: Test HungryMoose Test Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '12.x'
      - name: Run Tests
        run: ./gradlew clean check
        working-directory: ./hungry-moose-test
